//! Small host-owned session bindings, outside the opaque queue and agent checkout.
//! They are not credentials or permission grants. Unknown/in-flight sessions fail
//! closed after restart; the host must establish process and side-effect safety.
use crate::providers::{NativeProfile, ProviderKind};
use rand_core::{OsRng, RngCore};
use serde::{Deserialize, Serialize};
use std::fs::{self, OpenOptions};
use std::io::{self, Read, Write};
use std::os::unix::fs::{DirBuilderExt, OpenOptionsExt};
use std::path::{Path, PathBuf};

const LIMIT: u64 = 4096;
/// Server-owned session namespaces. Absence preserves the legacy role file.
/// An epoch starts a fresh provider history without changing old bindings.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RoleEpochs {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_epoch"
    )]
    pub developer: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_epoch"
    )]
    pub reviewer: Option<String>,
}
impl RoleEpochs {
    pub(crate) fn role(&self, reviewer: bool) -> Option<&str> {
        if reviewer {
            self.reviewer.as_deref()
        } else {
            self.developer.as_deref()
        }
    }

    pub(crate) fn validate(&self) -> io::Result<()> {
        for epoch in [&self.developer, &self.reviewer].into_iter().flatten() {
            validate_epoch(epoch)?;
        }
        Ok(())
    }
}

pub(crate) fn new_epoch() -> String {
    uuid()
}

fn deserialize_epoch<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<String>, D::Error> {
    let epoch = Option::<String>::deserialize(deserializer)?;
    if let Some(epoch) = &epoch {
        validate_epoch(epoch).map_err(serde::de::Error::custom)?;
    }
    Ok(epoch)
}

fn validate_epoch(epoch: &str) -> io::Result<()> {
    // Accept only the canonical random UUID format generated by this host. The
    // fixed byte shape also prevents path traversal and unbounded filenames.
    let bytes = epoch.as_bytes();
    if bytes.len() != 36
        || bytes.iter().enumerate().any(|(index, byte)| {
            if matches!(index, 8 | 13 | 18 | 23) {
                *byte != b'-'
            } else {
                !byte.is_ascii_digit() && !(b'a'..=b'f').contains(byte)
            }
        })
        || bytes[14] != b'4'
        || !matches!(bytes[19], b'8' | b'9' | b'a' | b'b')
    {
        Err(io::Error::other("invalid bounded role session epoch UUID"))
    } else {
        Ok(())
    }
}

fn session_path(root: &Path, role: &str, epoch: Option<&str>) -> io::Result<PathBuf> {
    match epoch {
        Some(epoch) => {
            validate_epoch(epoch)?;
            Ok(root.join(format!("{role}-{epoch}.json")))
        }
        None => Ok(root.join(format!("{role}.json"))),
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Record {
    version: u8,
    role: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "deserialize_epoch"
    )]
    epoch: Option<String>,
    cwd: PathBuf,
    profile_binding: String,
    session_id: Option<String>,
    ready: bool,
    #[serde(default)]
    attempt: u64,
}
pub(crate) struct Session {
    path: PathBuf,
    record: Record,
    pub resume: Option<String>,
    pub fresh_claude: Option<String>,
}
impl Session {
    pub fn begin(
        workspace: &Path,
        cwd: &Path,
        profile: &NativeProfile,
        read_only: bool,
        attempt: u64,
        require_resume: bool,
        epoch: Option<&str>,
    ) -> io::Result<Self> {
        let role = if read_only { "reviewer" } else { "developer" };
        let root = workspace.join("sessions");
        let path = session_path(&root, role, epoch)?;
        match fs::DirBuilder::new().mode(0o700).create(&root) {
            Ok(()) => {}
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {}
            Err(error) => return Err(error),
        }
        if !fs::symlink_metadata(&root)?.is_dir() || root.canonicalize()? != root {
            return Err(io::Error::other("session directory was redirected"));
        }
        let cwd = cwd.canonicalize()?;
        let binding = binding(profile)?;
        let existing = match OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_NOFOLLOW | libc::O_NONBLOCK)
            .open(&path)
        {
            Ok(file) => {
                if !file.metadata()?.is_file() {
                    return Err(io::Error::other("session record must be a regular file"));
                }
                let mut bytes = Vec::new();
                file.take(LIMIT + 1).read_to_end(&mut bytes)?;
                if bytes.len() as u64 > LIMIT {
                    return Err(io::Error::other("session record exceeds its bound"));
                }
                Some(serde_json::from_slice::<Record>(&bytes).map_err(io::Error::other)?)
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound => None,
            Err(error) => return Err(error),
        };
        if require_resume && existing.is_none() {
            return Err(io::Error::other(
                "continuation requires the selected role session record; refusing a fresh session",
            ));
        }
        let resume = if let Some(record) = existing {
            if record.version != 1
                || record.role != role
                || record.epoch.as_deref() != epoch
                || record.cwd != cwd
                || record.profile_binding != binding
            {
                return Err(io::Error::other(
                    "session binding changed; do not resume across task, role, workspace, or profile",
                ));
            }
            if !record.ready && record.attempt >= attempt {
                return Err(io::Error::other(
                    "prior session turn is not confirmed complete; inspect before recovery",
                ));
            }
            let id = record
                .session_id
                .ok_or_else(|| io::Error::other("completed session has no ID"))?;
            validate_id(&id)?;
            Some(id)
        } else {
            None
        };
        let fresh_claude = if resume.is_none() && profile.provider == ProviderKind::ClaudeCli {
            Some(uuid())
        } else {
            None
        };
        let record = Record {
            version: 1,
            role: role.into(),
            epoch: epoch.map(str::to_owned),
            cwd,
            profile_binding: binding,
            session_id: resume.clone().or(fresh_claude.clone()),
            ready: false,
            attempt,
        };
        let session = Self {
            path,
            record,
            resume,
            fresh_claude,
        };
        session.save()?; // Persist in-flight before a process can perform external effects.
        Ok(session)
    }
    pub(crate) fn verify_reviewer_resume(
        workspace: &Path,
        cwd: &Path,
        profile: &NativeProfile,
        attempt: u64,
        epoch: Option<&str>,
    ) -> io::Result<()> {
        let root = workspace.join("sessions");
        let path = session_path(&root, "reviewer", epoch)?;
        if !fs::symlink_metadata(&root)?.is_dir() || root.canonicalize()? != root {
            return Err(io::Error::other(
                "reviewer session directory missing or redirected",
            ));
        }
        let file = OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_NOFOLLOW | libc::O_NONBLOCK)
            .open(path)?;
        if !file.metadata()?.is_file() {
            return Err(io::Error::other(
                "reviewer session record must be a regular file",
            ));
        }
        let mut bytes = Vec::new();
        file.take(LIMIT + 1).read_to_end(&mut bytes)?;
        if bytes.len() as u64 > LIMIT {
            return Err(io::Error::other(
                "reviewer session record exceeds its bound",
            ));
        }
        let record: Record = serde_json::from_slice(&bytes).map_err(io::Error::other)?;
        if record.version != 1
            || record.role != "reviewer"
            || record.epoch.as_deref() != epoch
            || record.cwd != cwd.canonicalize()?
            || record.profile_binding != binding(profile)?
            || (!record.ready && record.attempt >= attempt)
        {
            return Err(io::Error::other(
                "reviewer session binding changed or prior turn is not confirmed complete",
            ));
        }
        validate_id(
            record
                .session_id
                .as_deref()
                .ok_or_else(|| io::Error::other("reviewer session ID checkpoint is missing"))?,
        )
    }
    pub fn checkpoint(&self) -> Checkpoint {
        Checkpoint {
            path: self.path.clone(),
            record: self.record.clone(),
        }
    }
    pub fn complete(mut self, id: Option<&str>) -> io::Result<()> {
        let id =
            id.ok_or_else(|| io::Error::other("provider did not return a resumable session ID"))?;
        validate_id(id)?;
        if self
            .record
            .session_id
            .as_deref()
            .is_some_and(|expected| expected != id)
        {
            return Err(io::Error::other("provider returned a different session ID"));
        }
        self.record.session_id = Some(id.into());
        self.record.ready = true;
        self.save()
    }
    fn save(&self) -> io::Result<()> {
        atomic_write(&self.path, &self.record)
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct Checkpoint {
    path: PathBuf,
    record: Record,
}
impl Checkpoint {
    pub fn started(&self, id: &str) -> io::Result<()> {
        validate_id(id)?;
        let mut record = self.record.clone();
        if record
            .session_id
            .as_deref()
            .is_some_and(|expected| expected != id)
        {
            return Err(io::Error::other("session checkpoint changed thread ID"));
        }
        record.session_id = Some(id.into());
        atomic_write(&self.path, &record)
    }
}
pub(crate) fn enabled(profile: &NativeProfile) -> bool {
    profile.provider == ProviderKind::CodexAppServer || profile.session_continuity
}
fn binding(profile: &NativeProfile) -> io::Result<String> {
    let mut profile = profile.clone();
    profile.env.retain(|key, _| !key.starts_with("RELAY_"));
    fingerprint(&profile)
}
pub(crate) fn fingerprint(value: &impl Serialize) -> io::Result<String> {
    // Configuration drift detection, not an authentication boundary. Never persist env secrets.
    let bytes = serde_json::to_vec(value).map_err(io::Error::other)?;
    let hash = bytes.iter().fold(0xcbf29ce484222325u64, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
    });
    Ok(format!("fnv1a-v1-{hash:016x}"))
}
pub(crate) fn atomic_write(path: &Path, value: &impl Serialize) -> io::Result<()> {
    let temporary = path.with_extension(format!("{}.tmp", uuid()));
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .custom_flags(libc::O_NOFOLLOW)
        .open(&temporary)?;
    let result = (|| {
        serde_json::to_writer(&mut file, value).map_err(io::Error::other)?;
        file.flush()?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        std::fs::File::open(path.parent().expect("metadata directory"))?.sync_all()
    })();
    if result.is_err() {
        let _ = fs::remove_file(temporary);
    }
    result
}

fn validate_id(id: &str) -> io::Result<()> {
    if id.is_empty()
        || id.len() > 256
        || !id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || b"-_".contains(&byte))
    {
        Err(io::Error::other("invalid bounded session ID"))
    } else {
        Ok(())
    }
}
fn uuid() -> String {
    let mut bytes = [0u8; 16];
    OsRng.fill_bytes(&mut bytes);
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    format!(
        "{}-{}-{}-{}-{}",
        &hex[..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..]
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn fixture() -> (tempfile::TempDir, PathBuf, NativeProfile) {
        let tmp = tempfile::TempDir::new().unwrap();
        let cwd = tmp.path().join("repository");
        fs::create_dir(&cwd).unwrap();
        let profile =
            serde_json::from_value(json!({"provider":"codex_app_server","program":"/bin/true"}))
                .unwrap();
        (tmp, cwd, profile)
    }

    #[test]
    fn role_epochs_are_optional_and_server_generated() {
        let empty: RoleEpochs = serde_json::from_value(json!({})).unwrap();
        assert_eq!(empty, RoleEpochs::default());
        assert_eq!(serde_json::to_value(&empty).unwrap(), json!({}));
        assert!(empty.role(false).is_none());
        assert!(empty.role(true).is_none());
        empty.validate().unwrap();

        let developer = new_epoch();
        let reviewer = new_epoch();
        assert_ne!(developer, reviewer);
        let roles: RoleEpochs = serde_json::from_value(json!({
            "developer": developer,
            "reviewer": reviewer,
        }))
        .unwrap();
        roles.validate().unwrap();
        assert_eq!(roles.role(false), Some(developer.as_str()));
        assert_eq!(roles.role(true), Some(reviewer.as_str()));
        assert!(serde_json::from_value::<RoleEpochs>(json!({"unknown": null})).is_err());
    }

    #[test]
    fn absent_epoch_preserves_legacy_record_bytes() {
        let legacy = r#"{"version":1,"role":"developer","cwd":"/tmp/repository","profile_binding":"fnv1a-v1-example","session_id":"thread-1","ready":true,"attempt":1}"#;
        let record: Record = serde_json::from_str(legacy).unwrap();
        assert!(record.epoch.is_none());
        assert_eq!(serde_json::to_string(&record).unwrap(), legacy);
    }

    #[test]
    fn invalid_epoch_is_rejected_before_filesystem_changes() {
        let (tmp, cwd, profile) = fixture();
        for epoch in [
            "",
            "../reviewer",
            "../00000000-0000-4000-8000-000000000000",
            "00000000/0000/4000/8000/000000000000",
            "00000000-0000-4000-8000-000000000000.json",
            "00000000-0000-4000-8000-00000000000",
            "00000000-0000-0000-0000-000000000000",
            "00000000-0000-4000-c000-000000000000",
            "00000000-0000-4000-8000-00000000000A",
            "00000000-0000-4000-8000-00000000000é",
        ] {
            assert!(validate_epoch(epoch).is_err(), "accepted {epoch:?}");
            for role in ["developer", "reviewer"] {
                assert!(serde_json::from_value::<RoleEpochs>(json!({role: epoch})).is_err());
            }
            let roles = RoleEpochs {
                developer: Some(epoch.into()),
                reviewer: None,
            };
            assert!(roles.validate().is_err());
            assert!(
                Session::begin(tmp.path(), &cwd, &profile, false, 1, false, Some(epoch)).is_err()
            );
            assert!(
                Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 1, Some(epoch))
                    .is_err()
            );
        }
        assert!(!tmp.path().join("sessions").exists());
        let oversized = "a".repeat(4096);
        assert!(validate_epoch(&oversized).is_err());
    }

    #[test]
    fn new_epoch_starts_fresh_for_same_provider_and_preserves_history() {
        let (tmp, cwd, profile) = fixture();
        Session::begin(tmp.path(), &cwd, &profile, false, 1, false, None)
            .unwrap()
            .complete(Some("legacy-thread"))
            .unwrap();
        let legacy_path = tmp.path().join("sessions/developer.json");
        let legacy_bytes = fs::read(&legacy_path).unwrap();

        let first_epoch = new_epoch();
        let first = Session::begin(
            tmp.path(),
            &cwd,
            &profile,
            false,
            2,
            false,
            Some(&first_epoch),
        )
        .unwrap();
        assert!(first.resume.is_none());
        assert!(first.fresh_claude.is_none());
        assert_eq!(
            first.path,
            tmp.path()
                .join(format!("sessions/developer-{first_epoch}.json"))
        );
        first.complete(Some("first-epoch-thread")).unwrap();
        let first_path = tmp
            .path()
            .join(format!("sessions/developer-{first_epoch}.json"));
        let first_bytes = fs::read(&first_path).unwrap();

        let second_epoch = new_epoch();
        let second = Session::begin(
            tmp.path(),
            &cwd,
            &profile,
            false,
            3,
            false,
            Some(&second_epoch),
        )
        .unwrap();
        assert!(second.resume.is_none());
        second.complete(Some("second-epoch-thread")).unwrap();
        assert_eq!(fs::read(legacy_path).unwrap(), legacy_bytes);
        assert_eq!(fs::read(first_path).unwrap(), first_bytes);
    }

    #[test]
    fn cross_provider_replacement_never_imports_session_ids() {
        let (tmp, cwd, codex) = fixture();
        let old_epoch = new_epoch();
        Session::begin(tmp.path(), &cwd, &codex, false, 1, false, Some(&old_epoch))
            .unwrap()
            .complete(Some("codex-thread"))
            .unwrap();
        let old_path = tmp
            .path()
            .join(format!("sessions/developer-{old_epoch}.json"));
        let old_bytes = fs::read(&old_path).unwrap();
        let claude: NativeProfile = serde_json::from_value(json!({
            "provider": "claude_cli", "program": "/bin/true", "session_continuity": true,
        }))
        .unwrap();
        assert!(
            Session::begin(tmp.path(), &cwd, &claude, false, 2, false, Some(&old_epoch)).is_err()
        );

        let new_epoch = new_epoch();
        let fresh =
            Session::begin(tmp.path(), &cwd, &claude, false, 2, false, Some(&new_epoch)).unwrap();
        assert!(fresh.resume.is_none());
        let fresh_id = fresh.fresh_claude.clone().unwrap();
        assert_ne!(fresh_id, "codex-thread");
        validate_epoch(&fresh_id).unwrap();
        fresh.complete(Some(&fresh_id)).unwrap();
        assert_eq!(fs::read(old_path).unwrap(), old_bytes);
    }

    #[test]
    fn unchanged_epoch_resumes_and_preserves_strict_inflight_rules() {
        let (tmp, cwd, profile) = fixture();
        let epoch = new_epoch();
        let first =
            Session::begin(tmp.path(), &cwd, &profile, false, 1, false, Some(&epoch)).unwrap();
        first.checkpoint().started("epoch-thread").unwrap();
        assert!(Session::begin(tmp.path(), &cwd, &profile, false, 1, false, Some(&epoch)).is_err());
        assert!(Session::begin(tmp.path(), &cwd, &profile, false, 0, false, Some(&epoch)).is_err());
        let recovered =
            Session::begin(tmp.path(), &cwd, &profile, false, 2, true, Some(&epoch)).unwrap();
        assert_eq!(recovered.resume.as_deref(), Some("epoch-thread"));
        recovered.complete(Some("epoch-thread")).unwrap();

        let resumed =
            Session::begin(tmp.path(), &cwd, &profile, false, 2, true, Some(&epoch)).unwrap();
        assert_eq!(resumed.resume.as_deref(), Some("epoch-thread"));
        assert!(resumed.complete(Some("different-thread")).is_err());
    }

    #[test]
    fn reviewer_checks_only_selected_epoch_without_legacy_fallback() {
        let (tmp, cwd, profile) = fixture();
        Session::begin(tmp.path(), &cwd, &profile, true, 1, false, None)
            .unwrap()
            .complete(Some("legacy-reviewer"))
            .unwrap();
        Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 2, None).unwrap();
        let epoch = new_epoch();
        assert!(
            Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 2, Some(&epoch)).is_err()
        );
        assert!(Session::begin(tmp.path(), &cwd, &profile, true, 2, true, Some(&epoch)).is_err());
        let fresh =
            Session::begin(tmp.path(), &cwd, &profile, true, 2, false, Some(&epoch)).unwrap();
        assert!(fresh.resume.is_none());
        assert!(
            Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 3, Some(&epoch)).is_err()
        );
        fresh.complete(Some("epoch-reviewer")).unwrap();
        Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 3, Some(&epoch)).unwrap();
        let resumed =
            Session::begin(tmp.path(), &cwd, &profile, true, 3, true, Some(&epoch)).unwrap();
        assert_eq!(resumed.resume.as_deref(), Some("epoch-reviewer"));
        assert!(
            Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 3, Some(&epoch)).is_err()
        );
        Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 4, Some(&epoch)).unwrap();
    }

    #[test]
    fn missing_session_id_never_silently_starts_fresh_in_selected_epoch() {
        let (tmp, cwd, profile) = fixture();
        let epoch = new_epoch();
        let session =
            Session::begin(tmp.path(), &cwd, &profile, false, 1, false, Some(&epoch)).unwrap();
        let path = session.path.clone();
        assert!(session.complete(None).is_err());
        let bytes = fs::read(&path).unwrap();
        for require_resume in [false, true] {
            let error = Session::begin(
                tmp.path(),
                &cwd,
                &profile,
                false,
                2,
                require_resume,
                Some(&epoch),
            )
            .err()
            .unwrap();
            assert!(error.to_string().contains("no ID"));
            assert_eq!(fs::read(&path).unwrap(), bytes);
        }
        // Only an explicit new namespace can create a fresh session.
        let fresh_epoch = new_epoch();
        assert!(
            Session::begin(
                tmp.path(),
                &cwd,
                &profile,
                false,
                2,
                false,
                Some(&fresh_epoch),
            )
            .unwrap()
            .resume
            .is_none()
        );
    }

    #[test]
    fn required_resume_rejects_missing_selected_epoch_after_prior_turn() {
        let (tmp, cwd, profile) = fixture();
        for reviewer in [false, true] {
            let epoch = new_epoch();
            let session =
                Session::begin(tmp.path(), &cwd, &profile, reviewer, 1, false, Some(&epoch))
                    .unwrap();
            let path = session.path.clone();
            session.complete(Some("checkpointed-thread")).unwrap();
            fs::remove_file(&path).unwrap();
            let error = Session::begin(tmp.path(), &cwd, &profile, reviewer, 2, true, Some(&epoch))
                .err()
                .unwrap();
            assert!(error.to_string().contains("refusing a fresh session"));
            assert!(!path.exists());
        }
    }

    #[test]
    fn corrupt_selected_epoch_never_falls_back_or_changes_old_records() {
        let (tmp, cwd, profile) = fixture();
        Session::begin(tmp.path(), &cwd, &profile, true, 1, false, None)
            .unwrap()
            .complete(Some("legacy-reviewer"))
            .unwrap();
        let legacy_path = tmp.path().join("sessions/reviewer.json");
        let legacy_bytes = fs::read(&legacy_path).unwrap();
        let epoch = new_epoch();
        let path = tmp.path().join(format!("sessions/reviewer-{epoch}.json"));
        fs::write(&path, b"{not a record}").unwrap();
        assert!(Session::begin(tmp.path(), &cwd, &profile, true, 2, false, Some(&epoch)).is_err());
        assert!(
            Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 2, Some(&epoch)).is_err()
        );
        assert_eq!(fs::read(&path).unwrap(), b"{not a record}");
        assert_eq!(fs::read(legacy_path).unwrap(), legacy_bytes);
    }

    #[test]
    fn records_cannot_be_imported_from_legacy_or_another_epoch() {
        let (tmp, cwd, profile) = fixture();
        Session::begin(tmp.path(), &cwd, &profile, true, 1, false, None)
            .unwrap()
            .complete(Some("legacy-reviewer"))
            .unwrap();
        let old_epoch = new_epoch();
        Session::begin(tmp.path(), &cwd, &profile, true, 1, false, Some(&old_epoch))
            .unwrap()
            .complete(Some("old-epoch-reviewer"))
            .unwrap();
        let epoch = new_epoch();
        let root = tmp.path().join("sessions");
        let destination = root.join(format!("reviewer-{epoch}.json"));
        for source in [
            root.join("reviewer.json"),
            root.join(format!("reviewer-{old_epoch}.json")),
        ] {
            let bytes = fs::read(&source).unwrap();
            fs::write(&destination, &bytes).unwrap();
            assert!(
                Session::begin(tmp.path(), &cwd, &profile, true, 2, false, Some(&epoch)).is_err()
            );
            assert!(
                Session::verify_reviewer_resume(tmp.path(), &cwd, &profile, 2, Some(&epoch))
                    .is_err()
            );
            assert_eq!(fs::read(&source).unwrap(), bytes);
            assert_eq!(fs::read(&destination).unwrap(), bytes);
        }
    }

    #[test]
    fn legacy_session_fingerprint_is_unchanged_and_native_mode_is_bound() {
        let mut profile: NativeProfile =
            serde_json::from_value(json!({"provider":"codex_cli","program":"/bin/true"})).unwrap();
        assert_eq!(binding(&profile).unwrap(), "fnv1a-v1-5b028b8dab7207b5");
        profile.native_permission = Some(crate::providers::NativePermission::CodexFullAccess);
        assert_ne!(binding(&profile).unwrap(), "fnv1a-v1-5b028b8dab7207b5");
    }
    #[test]
    fn sessions_reject_inflight_role_profile_and_cwd_mixups() {
        let tmp = tempfile::TempDir::new().unwrap();
        let cwd = tmp.path().join("repository");
        fs::create_dir(&cwd).unwrap();
        let profile: NativeProfile =
            serde_json::from_value(json!({"provider":"codex_app_server","program":"/bin/true"}))
                .unwrap();
        let session = Session::begin(tmp.path(), &cwd, &profile, false, 1, false, None).unwrap();
        assert!(Session::begin(tmp.path(), &cwd, &profile, false, 1, false, None).is_err());
        session.complete(Some("thread-1")).unwrap();
        let mut changed = profile.clone();
        changed.model = Some("different".into());
        assert!(Session::begin(tmp.path(), &cwd, &changed, false, 1, false, None).is_err());
        let other = tmp.path().join("other");
        fs::create_dir(&other).unwrap();
        assert!(Session::begin(tmp.path(), &other, &profile, false, 1, false, None).is_err());
        fs::copy(
            tmp.path().join("sessions/developer.json"),
            tmp.path().join("sessions/reviewer.json"),
        )
        .unwrap();
        assert!(Session::begin(tmp.path(), &cwd, &profile, true, 1, false, None).is_err());
        let resumed = Session::begin(tmp.path(), &cwd, &profile, false, 1, false, None).unwrap();
        assert_eq!(resumed.resume.as_deref(), Some("thread-1"));
        assert!(resumed.complete(Some("wrong-thread")).is_err());
    }
}
