// Run with: node app/tests/ui_merge_authorization_test.cjs
// Actual inline UI code, deterministic clock/network, no browser or external CLI required.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {webcrypto,createHash} = require('node:crypto');
let now = 1800000000000;
const Date = class extends globalThis.Date { constructor(...args) { super(...(args.length ? args : [now])); } static now() { return now; } };
const html = fs.readFileSync(require('node:path').resolve(__dirname, '../static/index.html'), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const clone = value => JSON.parse(JSON.stringify(value));
const settle = () => new Promise(resolve => setImmediate(resolve));
const task = (id, outcome = 'success') => ({id, key: 'task-' + id, payload: JSON.stringify({repository:'repo',requirements:'fixture',agent:'agent',test:null,publish:false,workspace_quota_bytes:100}), state:outcome ? 'finished':'queued', generation:outcome ? 1:0, owner:outcome ? 'host':null, result:outcome ? JSON.stringify({outcome,workspace:'/fixture',draft_pr:null}) : null, continuation_status:null});
const target = () => ({repository:'owner/project',repository_id:801,pr_id:901,pr_node_id:null,base_branch:'main',head_sha:'a'.repeat(40),head_branch:'relay/candidate',pr_number:19,pr_url:'https://github.com/owner/project/pull/19'});
const disclosureText = 'Exact-HEAD merge. HEAD lock and bypass_rules=false preserve rules. Base/stack/ready guards are not atomic. Observed stacks, queues and auto-merge are rejected. Accepted work may finish after revoke/expiry; no documented cancellation. Existing automation including configured branch deletion may run; Relay issues no separate delete/deploy/settings actions. Accepted does not mean merged.';
const disclosure = () => ({version:1,text:disclosureText,sha256:createHash('sha256').update(disclosureText).digest('hex')});
const policy = () => ({name:'exact-head',policy_digest:'b'.repeat(64),scope_digest:'c'.repeat(64),ci_track_id:10,ci_policy:'required-ci',ci_policy_digest:'d'.repeat(64),ci_source:{workflow_id:41,app_id:15368,event:'pull_request',required_jobs:['check','browser']},target:target(),merge_method:'squash',target_guard:'preflight_only',allow_ready:true,authorization_window_seconds:3600,poll_interval_seconds:60,deadline:Math.floor(Date.now()/1000)+3600});
const preview = () => ({eligible:true,reason:null,policies:[policy()],risk_disclosure:disclosure(),authorizations:[],lane_diagnostic:null});
const disabled = () => ({eligible:false,reason:'No trustworthy identity',policies:[],risk_disclosure:null,authorizations:[],lane_diagnostic:null});
const requestBody = (p=policy()) => ({key:'fixture',confirm_merge:true,policy:p.name,policy_digest:p.policy_digest,ci_track_id:p.ci_track_id,scope_digest:p.scope_digest,deadline:p.deadline,allow_ready:false,accept_non_atomic_target_guard:true,deadline_semantics:'last_dispatch',accept_existing_automation:true,risk_disclosure_version:1,risk_disclosure_sha256:disclosure().sha256});
const record = (body=requestBody(), p=policy()) => ({id:20,publication_task_id:1,ci_track_id:p.ci_track_id,policy:p.name,policy_digest:p.policy_digest,scope_digest:p.scope_digest,ci_policy:p.ci_policy,ci_policy_digest:p.ci_policy_digest,ci_source:clone(p.ci_source),target:clone(p.target),resolved_pr_node_id:null,merge_method:p.merge_method,target_guard:p.target_guard,allow_ready:body.allow_ready,authorization_window_seconds:p.authorization_window_seconds,poll_interval_seconds:p.poll_interval_seconds,created_at:Math.floor(Date.now()/1000),deadline:body.deadline,consent:Object.fromEntries(Object.entries(body).filter(([key])=>key!=='key')),status:'watching',revision:1,attempt:0,revoked:false,ready_dispatched:false,merge_dispatched:false,ready_confirmed:false,merge_failed_confirmed:false,async_request:null,merge_commit_sha:null,last_observed_at:null,next_poll_at:0,latest_evidence:null,diagnostic:null,remote_merge_eligibility:'not_established',observation_only:false,observed_remote_status:null});
const accepted = (body=requestBody(),p=policy()) => ({...record(body,p),status:'accepted',merge_dispatched:true,async_request:{id:'123e4567-e89b-42d3-a456-426614174000',options:{sha:p.target.head_sha,merge_method:p.merge_method,merge_action:'direct_merge',bypass_rules:false},provenance:'relay'}});
const action = () => ({id:'publish_approved',allowed:true,ordinary_allowed:true,candidate_sha:'a'.repeat(40),base_sha:'b'.repeat(40),github_repository:'owner/project',base_branch:'main',draft_pr_adapter:'publish',publisher_binding:'c'.repeat(64),draft:true,dry_run:false,requires_prior_test_acceptance:true,authorization_ttl_seconds:86400,expires_at_unix_seconds:null});
const operator = t => ({task_id:t.id,generation:t.generation,failure:null,resources:{usage:{logical_bytes:150,complete:true,measured_at:1700000000,reason:null},quota_bytes:1000,host_policy_cap_bytes:1000,snapshot_cap_bytes:800,enforcement:'logical_bytes_best_effort',os_hard_quota:false,disk_reserved:false},retained_result:{available:Boolean(t.result),immutable:true},workspace_retained:true,recovery:{inherited_quota_bytes:1000,actions:t.result?[action()]:[],blocked_reason:null,successor_id:null,reserved_request:null}});
const estimate = () => ({host_policy_cap_bytes:1000,default_quota_bytes:1000,snapshot_cap_bytes:800,initial_estimate:{source:'host_inventory',snapshot_bytes:100,git_metadata_reference_bytes:20,reviewer_copy_bytes:100,estimated_initial_bytes:220,complete:true,notes:['initial inventory only']},build_growth:'unknown',enforcement:'logical_bytes_best_effort',os_hard_quota:false,disk_reserved:false});
function fixture(authMode = 'bearer') {
  const nodes = new Map(), events = new Map(), timers = new Map(); let active = null, timerId = 0;
  class Element {
    constructor(tag = 'div', id = '') { this.tagName = tag.toUpperCase(); this.id = id; this.children = []; this.dataset = {}; this.attrs = {}; this.events = new Map(); this.hidden = false; this.disabled = false; this.open = false; this._text = ''; this._value = ''; this.className = ''; this.classList = {toggle: () => {}}; }
    get value() { return this._value; } set value(value) { this._value = String(value); }
    get textContent() { return this._text + this.children.map(child => child.textContent || '').join(''); } set textContent(value) { this._text = String(value); this.children = []; }
    set innerHTML(_) { throw new Error('Unsafe HTML rendering'); }
    append(...children) { this.children.push(...children); if (this.tagName === 'SELECT' && this.children.length === children.length) this.value = children[0]?.value || ''; }
    replaceChildren(...children) { this._text = ''; this.children = []; this.append(...children); }
    setAttribute(key, value) { this.attrs[key] = String(value); } getAttribute(key) { return this.attrs[key] ?? null; }
    addEventListener(name, fn) { this.events.set(name, [...this.events.get(name) || [], fn]); } removeEventListener() {}
    focus() { active = this; } showModal() { this.open = true; } close() { this.open = false; return this.emit('close'); }
    querySelectorAll(tag) { return this.children.flatMap(child => [...(child.tagName === tag.toUpperCase() ? [child] : []), ...child.querySelectorAll(tag)]); }
    emit(name, extra = {}) { return Promise.all((this.events.get(name) || []).map(fn => fn({preventDefault() {}, ...extra}))); }
  }
  for (const match of html.matchAll(/<([a-z0-9]+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)) { const node = new Element(match[1], match[3]); node.hidden = /\bhidden\b/.test(match[2]); node.disabled = /\bdisabled\b/.test(match[2]); nodes.set(match[3], node); }
  const filters = ['all', 'queued', 'claimed', 'finished'].map(filter => { const node = new Element('button'); node.dataset.filter = filter; return node; });
  const document = {getElementById: id => { assert(nodes.has(id), id); return nodes.get(id); }, createElement: tag => new Element(tag), querySelectorAll: () => filters, documentElement: new Element('html'), get activeElement() { return active; }};
  const f = {nodes, events, timers, requests:[], pending:[], posts:[], tasks:[task(2,null),task(1)], operators:new Map(), estimate:estimate(), status:{active:null,recovery_required:false,diagnostic:null}, postMode:'success', operatorError:0, estimateError:0, delay:()=>false, ignoreAbort:false, responseQuota:null,logoutError:false,responseMismatch:false,failureCode:null,merge:preview(),mergeError:0};
  for (const t of f.tasks) f.operators.set(t.id,operator(t));
  const $ = id => nodes.get(id); f.$ = $;
  f.resourceReads = () => f.requests.filter(r=>r.url.startsWith('/api/resources')||r.url.endsWith('/operator'));
  f.login = async () => { $('token').value='test-token'; $('username').value='operator'; $('password').value='password'; await $('auth-form').emit('submit'); await settle(); };
  f.select = async id => { await $('task-list').querySelectorAll('button').find(b=>b.dataset.taskId===String(id)).emit('click'); await settle(); };
  f.resolve = url => { const i=f.pending.findIndex(p=>p.url===url); assert(i>=0,'missing '+url); f.pending.splice(i,1)[0].resolve(); };
  f.flush = async () => { for (const [id,timer] of [...timers]) if(timer.milliseconds===2000){timers.delete(id);await timer.callback();} await settle(); };
  async function fetch(url, opts) {
    f.requests.push({url,opts}); let data,status=200;
    assert.equal(opts.headers.Authorization,authMode==='bearer'&&url.startsWith('/api/')?'Bearer test-token':undefined);
    if(url==='/auth/status')data={mode:authMode,authenticated:false};
    else if(url==='/auth/login')data={authenticated:true};
    else if(url==='/auth/logout'){if(f.logoutError)throw new TypeError('logout failed');data={authenticated:false};}
    else if(url.endsWith('/merge-preview')){data=Number(url.split('/').at(-2))===1?f.merge:disabled();if(f.mergeError){status=f.mergeError;data={error:'Merge unavailable'};}}
    else if(url.endsWith('/merge-authorizations'))data=[];
    else if (url==='/api/config')data={repositories:['repo','other'],agents:['agent'],tests:['test'],workflows:[{name:'review / flow',repository:'repo',developer:'agent',reviewer:'agent',test:'test',max_repairs:0}]};
    else if(url==='/api/status')data=f.status;
    else if(url==='/api/tasks'&&opts.method==='GET')data=f.tasks;
    else if(url.startsWith('/api/resources?')){data=f.estimate;if(f.estimateError){status=f.estimateError;data={error:'estimate unavailable'};}}
    else if(url.endsWith('/ci-preview'))data={eligible:false,reason:'CI disabled',publication:null,policies:[],tracks:[],remote_merge_eligibility:'not_established'};
    else if(url.endsWith('/operator')){data=f.operators.get(Number(url.split('/').at(-2)));if(f.operatorError){status=f.operatorError;data={error:'operator unavailable'};}}
    else if(opts.method==='POST'){
      const body=JSON.parse(opts.body); f.posts.push({url,body});
      if(f.postMode==='abort')throw new TypeError('lost response');
      if(['401','409','422'].includes(f.postMode)){status=Number(f.postMode);data={error:'host policy changed',failure:f.failureCode?{code:f.failureCode}:null};}
      else {
        if(url.endsWith('/authorize-merge')){
          data=f.merge.authorizations.find(record=>Object.entries(body).every(([key,value])=>key==='key'||record.consent[key]===value));
          if(!data)data={...record(body,f.merge.policies[0]),id:Math.max(19,...f.merge.authorizations.map(record=>record.id))+1,previous_authorization_id:f.merge.replacement_authorization_id??null};
          if(f.postMode!=='unverifiable')f.merge.authorizations=[data,...f.merge.authorizations.filter(record=>record.id!==data.id)];
        }else{
          const previous=f.merge.authorizations[0];assert(previous);assert.equal(body.expected_revision,previous.revision);
          data={...previous,revision:previous.revision+1,...(url.endsWith('/revoke')?{revoked:true,status:previous.async_request?previous.status:'revoked'}:{status:'watching',observation_only:true})};
          if(f.postMode!=='unverifiable')f.merge.authorizations=[data];
        }
        if(f.postMode==='lost_after_commit')throw new TypeError('committed, response lost');
        if(f.responseMismatch)data={...data,target:{...data.target,head_sha:'b'.repeat(40)}};
      }
    } else data=f.tasks.find(t=>t.id===Number(url.split('/').at(-1)));
    const snapshot=clone(data),response={ok:status===200,status,json:async()=>clone(snapshot)};
    if(f.delay(url,opts))return new Promise((resolve,reject)=>{f.pending.push({url,resolve:()=>resolve(response)});if(!f.ignoreAbort)opts.signal.addEventListener('abort',()=>{const e=new Error('abort');e.name='AbortError';reject(e);});});
    return response;
  }
  const context = {console,document,window:{matchMedia:()=>({matches:false,addEventListener(){}}),addEventListener:(name,fn)=>events.set(name,fn)},navigator:{},fetch,crypto:webcrypto,AbortController,TextEncoder,Uint8Array,Date,Error,JSON,Array,String,Number,Boolean,Set,Map,encodeURIComponent,setTimeout:(callback,milliseconds)=>{const id=++timerId;timers.set(id,{callback,milliseconds});return id;},clearTimeout:id=>timers.delete(id)};
  Object.defineProperties(context,{localStorage:{get(){throw Error('must not use storage')}},sessionStorage:{get(){throw Error('must not use storage')}}});
  vm.runInNewContext(script,context);return f;
}
async function ready(mode='bearer') { const f=fixture(mode); await settle(); await f.login(); await f.select(1); return f; }
const controls = f => f.$('merge-records').querySelectorAll('button');
const control = (f, action) => controls(f).find(button => button.dataset.mergeAction === action);
async function authorize(f,allowReady=false) { await f.$('merge-authorize').emit('click'); assert(f.$('merge-dialog').open); f.$('merge-allow-ready').checked=allowReady;f.$('merge-accept').checked=true;await f.$('merge-accept').emit('change');return f.$('merge-confirm').emit('click'); }
const watchdog=setTimeout(()=>{console.error('Merge UI tests did not finish');process.exit(1)},5000);
(async()=>{
  const f=await ready(),$=f.$;
  assert(!$('detail-merge').hidden);assert(!$('merge-authorize').disabled);assert.equal(f.posts.length,0);
  await $('merge-authorize').emit('click');assert($('merge-dialog').open);assert($('merge-confirm').disabled);assert(!$('merge-accept').checked);assert(!$('merge-allow-ready').checked);
  for(const text of ['owner/project','#19','a'.repeat(40),'main','squash','Repository ID：801','PR ID：901','Workflow ID：41','App ID：15368','required-ci','check','browser','3600','范围摘要','风险说明摘要'])assert($('merge-dialog-scope').textContent.includes(text),text);
  assert.equal($('merge-disclosure').textContent,disclosureText);
  await $('merge-confirm').emit('click');assert.equal(f.posts.length,0);$('merge-allow-ready').checked=true;await $('merge-allow-ready').emit('change');assert($('merge-confirm').disabled);
  await $('merge-dismiss').emit('click');assert(!$('merge-dialog').open);assert(!$('merge-allow-ready').checked);await $('merge-confirm').emit('click');assert.equal(f.posts.length,0);
  await $('merge-authorize').emit('click');$('merge-accept').checked=true;await $('merge-accept').emit('change');await $('merge-dialog').emit('cancel');await $('merge-confirm').emit('click');assert.equal(f.posts.length,0);
  await $('refresh').emit('click');await f.flush();assert.equal(f.posts.length,0,'local polling never authorizes');
  await authorize(f,true);assert.equal(f.posts.length,1);assert.deepEqual(f.posts[0].body,{...requestBody(),key:f.posts[0].body.key,allow_ready:true});assert(!$('merge-dialog').open);assert($('merge-authorize').hidden);assert.match($('merge-records').textContent,/已授权，等待最新/);assert(control(f,'revoke'));
  await control(f,'revoke').emit('click');assert.deepEqual(f.posts[1].body,{expected_revision:1});assert.match($('merge-records').textContent,/已撤销/);assert(!control(f,'revoke'));
  await control(f,'reconcile').emit('click');assert.deepEqual(f.posts[2].body,{expected_revision:2});assert.equal(f.posts[2].url,'/api/merge-authorizations/20/reconcile');assert.match($('merge-records').textContent,/已撤销/);assert.match($('merge-records').textContent,/只读核对中/);
  // Accepted/pending are never displayed as merged. Late merge is allowed after revoke/expiry.
  for(const revoked of [false,true]){
    const a=await ready();a.merge.authorizations=[{...accepted(),revoked}];await a.$('merge-read').emit('click');assert.match(a.$('merge-records').textContent,/请求已受理.*尚未合并/);assert(!a.$('merge-records').textContent.includes('已确认 Relay 请求合并完成'));
    for(const status of ['pending','expired','merged']){a.merge.authorizations[0]={...a.merge.authorizations[0],status,revision:a.merge.authorizations[0].revision+1};await a.$('merge-read').emit('click');}
    assert.match(a.$('merge-records').textContent,/已确认 Relay 请求合并完成/);assert.equal(a.posts.length,0);assert.equal(controls(a).length,0);
  }
  const external=await ready();external.merge.authorizations=[{...record(),status:'externally_merged'}];await external.$('merge-read').emit('click');assert.match(external.$('merge-records').textContent,/非 Relay 合并确认/);assert(!external.$('merge-records').textContent.includes('已确认 Relay 请求合并完成'));
  const unknown=await ready();unknown.merge.authorizations=[{...record(),status:'process_unknown',diagnostic:{code:'merge_local_recovery_required',message:'Inspect trusted local owner'}}];await unknown.$('merge-read').emit('click');assert(!control(unknown,'reconcile'));assert.match(unknown.$('merge-records').textContent,/本机恢复/);assert.equal(unknown.posts.length,0);unknown.merge.authorizations[0].status='effect_unknown';unknown.merge.authorizations[0].revision++;await unknown.$('merge-read').emit('click');await control(unknown,'reconcile').emit('click');assert.equal(unknown.posts.length,1);assert.equal(unknown.posts[0].url,'/api/merge-authorizations/20/reconcile');
  // Only the authoritative safe predecessor pointer permits a new explicit linked consent.
  for(const previous of [{...record(),status:'expired'},{...record(),status:'revoked',revoked:true},{...record(),status:'expired',ready_dispatched:true,ready_confirmed:true},{...accepted(),status:'failed',merge_failed_confirmed:true}]){
    const replacement=await ready();replacement.merge.authorizations=[previous];replacement.merge.replacement_authorization_id=20;replacement.merge.policies[0].scope_digest='e'.repeat(64);await replacement.$('merge-read').emit('click');assert(!replacement.$('merge-authorize').disabled);await replacement.$('merge-authorize').emit('click');assert.match(replacement.$('merge-dialog-scope').textContent,/旧授权 #20/);replacement.$('merge-accept').checked=true;await replacement.$('merge-accept').emit('change');await replacement.$('merge-confirm').emit('click');assert.equal(replacement.posts.length,1);assert.equal(replacement.posts[0].body.scope_digest,'e'.repeat(64));assert.equal(replacement.merge.authorizations[0].previous_authorization_id,20);assert.match(replacement.$('merge-records').textContent,/授权 #21/);
  }
  const otherPublication=await ready();otherPublication.merge.authorizations=[{...record(),publication_task_id:9,status:'expired'}];otherPublication.merge.replacement_authorization_id=20;otherPublication.merge.policies[0].scope_digest='e'.repeat(64);await otherPublication.$('merge-read').emit('click');assert.match(otherPublication.$('merge-records').textContent,/原发布任务 #9/);assert(!otherPublication.$('merge-authorize').disabled);await authorize(otherPublication);assert.equal(otherPublication.posts.length,1);assert.equal(otherPublication.merge.authorizations[0].publication_task_id,1);
  const wrongRemote=await ready();wrongRemote.merge.authorizations=[{...record(),publication_task_id:9,status:'expired',target:{...target(),repository_id:999}}];wrongRemote.merge.replacement_authorization_id=20;await wrongRemote.$('merge-read').emit('click');assert(wrongRemote.$('merge-authorize').disabled);assert.match(wrongRemote.$('merge-error').textContent,/不匹配/);
  const badPredecessor=await ready();badPredecessor.merge.authorizations=[{...record(),status:'expired'}];badPredecessor.merge.replacement_authorization_id=99;await badPredecessor.$('merge-read').emit('click');assert(badPredecessor.$('merge-authorize').disabled);await badPredecessor.$('merge-authorize').emit('click');assert(!badPredecessor.$('merge-dialog').open);
  // A lost response freezes every byte of consent, including original dispatch deadline.
  const lost=await ready();lost.postMode='abort';await authorize(lost);const first=clone(lost.posts[0]);assert.match(lost.$('merge-error').textContent,/尚未确认/);assert(lost.$('merge-policy').disabled);lost.merge.policies[0].deadline+=60;await lost.$('merge-read').emit('click');await lost.$('merge-authorize').emit('click');assert.deepEqual(lost.posts[1],first);assert(!lost.$('merge-dialog').open);
  lost.postMode='401';await lost.$('merge-authorize').emit('click');assert(!lost.$('auth-panel').hidden);assert(lost.$('detail-merge').hidden);await lost.login();await lost.select(1);lost.postMode='422';await lost.$('merge-authorize').emit('click');assert.deepEqual(lost.posts.at(-1),first);lost.postMode='success';await lost.$('merge-authorize').emit('click');assert.deepEqual(lost.posts.at(-1),first);assert(lost.$('merge-authorize').hidden);
  const committed=await ready();committed.postMode='lost_after_commit';await authorize(committed);await committed.$('merge-read').emit('click');assert(committed.$('merge-authorize').hidden);assert.equal(committed.posts.length,1);
  const invalidResponse=await ready();invalidResponse.postMode='unverifiable';invalidResponse.responseMismatch=true;await authorize(invalidResponse);const frozen=clone(invalidResponse.posts[0]);assert.match(invalidResponse.$('merge-error').textContent,/尚未确认/);assert.equal(invalidResponse.$('merge-records').children.length,0);invalidResponse.responseMismatch=false;await invalidResponse.$('merge-authorize').emit('click');assert.deepEqual(invalidResponse.posts[1],frozen);
  const duplicate=await ready();duplicate.delay=(_url,opts)=>opts.method==='POST';const duplicatePost=authorize(duplicate);await settle();await duplicate.$('merge-confirm').emit('click');await duplicate.$('merge-authorize').emit('click');assert.equal(duplicate.posts.length,1);duplicate.resolve('/api/tasks/1/authorize-merge');await duplicatePost;
  // Definitive rejection requires a fresh preview and meaningful new consent; ambiguous rejection does not.
  const denied=await ready();denied.postMode='409';await authorize(denied);const deniedKey=denied.posts[0].body.key;assert(denied.$('merge-authorize').disabled);await denied.$('merge-read').emit('click');denied.postMode='success';await authorize(denied);assert.notEqual(denied.posts[1].body.key,deniedKey);
  for(const mutate of [p=>p.policy_digest='e'.repeat(64),p=>p.scope_digest='f'.repeat(64),p=>p.target.head_sha='b'.repeat(40),p=>p.target.base_branch='release',p=>p.target.repository_id++,p=>p.target.pr_id++,p=>p.ci_source.workflow_id++,p=>p.ci_source.app_id++,p=>p.ci_source.required_jobs=['different'],p=>p.ci_policy_digest='e'.repeat(64),p=>p.merge_method='rebase',p=>p.allow_ready=false]){
    const changed=await ready();changed.postMode='abort';await authorize(changed);mutate(changed.merge.policies[0]);await changed.$('merge-read').emit('click');assert(changed.$('merge-authorize').disabled);await changed.$('merge-authorize').emit('click');assert.equal(changed.posts.length,1);
  }
  const dialogDrift=await ready();await dialogDrift.$('merge-authorize').emit('click');dialogDrift.$('merge-accept').checked=true;dialogDrift.merge.policies[0].target.head_sha='b'.repeat(40);await dialogDrift.$('merge-read').emit('click');assert(!dialogDrift.$('merge-dialog').open);await dialogDrift.$('merge-confirm').emit('click');assert.equal(dialogDrift.posts.length,0);
  const expiry=await ready();await expiry.$('merge-authorize').emit('click');expiry.$('merge-accept').checked=true;now+=3601000;await expiry.$('merge-confirm').emit('click');assert.equal(expiry.posts.length,0);assert(!expiry.$('merge-dialog').open);now=1800000000000;
  const readonly=await ready();readonly.merge.policies[0].allow_ready=false;await readonly.$('merge-read').emit('click');await authorize(readonly,true);assert.equal(readonly.posts[0].body.allow_ready,false);
  // Strict identity, disclosure and source validation; untrusted text only reaches textContent.
  for(const mutate of [p=>p.policies[0].target.pr_url='javascript:alert(1)',p=>p.policies[0].target.repository_id='801',p=>p.policies[0].target.pr_id=0,p=>p.policies[0].target.head_sha='bad',p=>p.policies[0].ci_source.event='push',p=>p.policies[0].ci_source.app_id='15368',p=>p.policies[0].ci_source.required_jobs=[],p=>p.risk_disclosure.sha256='0'.repeat(64),p=>p.risk_disclosure.text+=' forged']){const malformed=await ready();mutate(malformed.merge);await malformed.$('merge-read').emit('click');assert(malformed.$('merge-authorize').disabled);assert.match(malformed.$('merge-error').textContent,/不匹配/);assert.equal(malformed.posts.length,0);}
  const safe=await ready(),attack='<img src=x onerror=alert(1)>';safe.merge.policies[0].target.base_branch=attack;safe.merge.policies[0].ci_source.required_jobs=[attack];await safe.$('merge-read').emit('click');await safe.$('merge-authorize').emit('click');assert(safe.$('merge-dialog-scope').textContent.includes(attack));assert.equal(safe.$('detail-merge').querySelectorAll('img').length,0);assert.equal(safe.$('merge-dialog').querySelectorAll('img').length,0);
  for(const mutate of [r=>r.target.repository_id++,r=>r.target.pr_id++,r=>r.target.base_branch='other',r=>r.ci_source.workflow_id++,r=>r.consent.allow_ready=!r.allow_ready,r=>r.async_request.options.bypass_rules=true,r=>r.async_request.id='00000000-0000-0000-0000-000000000000']){const drift=await ready();drift.merge.authorizations=[accepted()];await drift.$('merge-read').emit('click');mutate(drift.merge.authorizations[0]);drift.merge.authorizations[0].revision++;await drift.$('merge-read').emit('click');assert.match(drift.$('merge-error').textContent,/不匹配|已变化/);assert.equal(controls(drift).length,0);}
  // Late GETs and POSTs cannot regress a newer revision or hide a newly created authorization.
  const old=await ready();await authorize(old);const snapshot=clone(old.merge.authorizations[0]);await control(old,'revoke').emit('click');old.merge.authorizations=[snapshot];await old.$('merge-read').emit('click');assert.match(old.$('merge-error').textContent,/旧修订/);assert.equal(controls(old).length,0);
  const missing=await ready();missing.delay=url=>url.endsWith('/merge-preview');missing.ignoreAbort=true;const staleRead=missing.$('merge-read').emit('click');await settle();missing.delay=()=>false;const saved=record();missing.merge.authorizations=[saved];await missing.$('merge-read').emit('click');missing.resolve('/api/tasks/1/merge-preview');await staleRead;assert.match(missing.$('merge-records').textContent,/授权 #20/);
  const racing=await ready();racing.delay=(url,opts)=>url.endsWith('/authorize-merge')&&opts.method==='POST';const raced=authorize(racing);await settle();racing.merge.authorizations[0]={...racing.merge.authorizations[0],revision:3,status:'pending'};await racing.$('merge-read').emit('click');racing.resolve('/api/tasks/1/authorize-merge');await raced;assert.match(racing.$('merge-records').textContent,/修订 3/);assert.match(racing.$('merge-records').textContent,/GitHub 请求处理中/);
  const readPostRace=await ready();readPostRace.postMode='unverifiable';readPostRace.ignoreAbort=true;readPostRace.delay=url=>url.endsWith('/authorize-merge')||url.endsWith('/merge-preview');const postFirst=authorize(readPostRace);await settle();const emptyRead=readPostRace.$('merge-read').emit('click');await settle();readPostRace.resolve('/api/tasks/1/authorize-merge');await postFirst;readPostRace.resolve('/api/tasks/1/merge-preview');await emptyRead;assert.match(readPostRace.$('merge-error').textContent,/旧修订/);assert(readPostRace.$('merge-authorize').disabled);assert.equal(readPostRace.posts.length,1);
  const staleControl=await ready();await authorize(staleControl);staleControl.postMode='abort';await control(staleControl,'revoke').emit('click');const originalControl=clone(staleControl.posts.at(-1));staleControl.merge.authorizations[0].revision++;await staleControl.$('merge-read').emit('click');staleControl.postMode='409';await control(staleControl,'revoke').emit('click');assert.deepEqual(staleControl.posts.at(-1),originalControl);assert.equal(controls(staleControl).length,0);await staleControl.$('merge-read').emit('click');staleControl.postMode='success';await control(staleControl,'revoke').emit('click');assert.equal(staleControl.posts.at(-1).body.expected_revision,2);
  // Close/navigation/history/logout/auth expiry fence stale dialogs, controls and completions.
  const nav=await ready();await nav.$('merge-authorize').emit('click');nav.$('merge-accept').checked=true;await nav.select(2);assert(!nav.$('merge-dialog').open);await nav.$('merge-confirm').emit('click');assert.equal(nav.posts.length,0);assert(nav.$('detail-merge').hidden);
  const history=await ready();await history.$('merge-authorize').emit('click');history.$('merge-accept').checked=true;history.events.get('popstate')();assert(!history.$('merge-dialog').open);await history.$('merge-confirm').emit('click');assert.equal(history.posts.length,0);assert(history.$('merge-authorize').disabled);await history.$('merge-read').emit('click');assert(!history.$('merge-authorize').disabled);
  const late=await ready();late.delay=(_url,opts)=>opts.method==='POST';late.ignoreAbort=true;const response=authorize(late);await settle();await late.select(2);late.resolve('/api/tasks/1/authorize-merge');await response;assert.equal(late.$('detail-title').textContent,'任务 #2');assert(late.$('detail-merge').hidden);
  for(const mode of ['bearer','session','hybrid']){const auth=await ready(mode);await auth.$('merge-authorize').emit('click');auth.$('merge-accept').checked=true;await auth.$('logout').emit('click');assert(!auth.$('merge-dialog').open);await auth.$('merge-confirm').emit('click');assert.equal(auth.posts.length,0);await auth.login();await auth.select(1);auth.delay=(url,opts)=>url.endsWith('/authorize-merge')&&opts.method==='POST';auth.ignoreAbort=true;const pending=authorize(auth);await settle();await auth.$('logout').emit('click');auth.resolve('/api/tasks/1/authorize-merge');await pending;assert(auth.$('detail-merge').hidden);assert.equal(auth.$('merge-policy-scope').textContent,'');assert.equal(auth.posts.length,1);}
  const expiredAuth=await ready('session');await expiredAuth.$('merge-authorize').emit('click');expiredAuth.$('merge-accept').checked=true;expiredAuth.mergeError=401;await expiredAuth.$('merge-read').emit('click');assert(!expiredAuth.$('merge-dialog').open);await expiredAuth.$('merge-confirm').emit('click');assert.equal(expiredAuth.posts.length,0);
  console.log('PASS: explicit merge consent; default-off/optional ready; immutable scope/source/disclosure and frozen retries; pending versus merged; revoke/expiry late result; read-only unknown reconcile; revision/identity fencing; safe DOM; duplicate, cancel, auth and navigation races');
})().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>clearTimeout(watchdog));
