// Run with: node app/tests/ui_capabilities_test.cjs
// Actual inline UI code, deterministic clock/network, no browser or external CLI required.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {webcrypto} = require('node:crypto');
const html = fs.readFileSync(require('node:path').resolve(__dirname, '../static/index.html'), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const clone = value => JSON.parse(JSON.stringify(value));
const settle = () => new Promise(resolve => setImmediate(resolve));
const task = (id, outcome = 'failure') => ({id, key: 'task-' + id, payload: JSON.stringify({repository:'repo',requirements:'fixture',agent:'agent',test:null,publish:false,workspace_quota_bytes:100}), state:outcome ? 'finished':'queued', generation:outcome ? 1:0, owner:outcome ? 'host':null, result:outcome ? JSON.stringify({outcome,workspace:'/fixture',draft_pr:null}) : null, continuation_status:null});
const action = (id = 'retry') => ({id,quota_increase_allowed:true,quota_increase_required:true,min_quota_bytes:151,max_quota_bytes:1000,requires_test_revalidation:id==='continue_review'});
const operator = t => ({task_id:t.id,generation:t.generation,failure:t.result ? {code:'workspace_quota_exceeded',stage:'test',cause:'logical workspace limit reached'} : null, resources:{usage:{logical_bytes:150,complete:true,measured_at:1700000000,reason:null},quota_bytes:100,host_policy_cap_bytes:1000,snapshot_cap_bytes:800,enforcement:'logical_bytes_best_effort',os_hard_quota:false,disk_reserved:false},retained_result:{available:Boolean(t.result),immutable:true},workspace_retained:true,recovery:{inherited_quota_bytes:100,actions:t.result ? [action(),action('continue_review')] : [],blocked_reason:null,successor_id:null,reserved_request:null}});
const estimate = () => ({host_policy_cap_bytes:1000,default_quota_bytes:1000,snapshot_cap_bytes:800,initial_estimate:{source:'host_inventory',snapshot_bytes:100,git_metadata_reference_bytes:20,reviewer_copy_bytes:100,estimated_initial_bytes:220,complete:true,notes:['initial inventory only']},build_growth:'unknown',enforcement:'logical_bytes_best_effort',os_hard_quota:false,disk_reserved:false});
function fixture(authMode = 'bearer') {
  const nodes = new Map(), events = new Map(), timers = new Map(); let active = null, timerId = 0;
  class Element {
    constructor(tag = 'div', id = '') { this.tagName = tag.toUpperCase(); this.id = id; this.children = []; this.dataset = {}; this.attrs = {}; this.events = new Map(); this.hidden = false; this.disabled = false; this.open = false; this._text = ''; this._value = ''; this.className = ''; this.classList = {toggle: () => {}}; }
    get value() { return this._value; } set value(value) { this._value = String(value); }
    get textContent() { return this._text + this.children.map(child => child.textContent || '').join(''); } set textContent(value) { this._text = String(value); this.children = []; }
    set innerHTML(_) { throw new Error('Unsafe HTML rendering'); }
    append(...children) { this.children.push(...children); if (this.tagName === 'SELECT' && this.children.length === children.length) this.value = children[0]?.value || ''; }
    replaceChildren(...children) { this._text = ''; this.children = []; this.append(...children); }
    setAttribute(key, value) { this.attrs[key] = String(value); } getAttribute(key) { return this.attrs[key] ?? null; }
    addEventListener(name, fn) { this.events.set(name, [...this.events.get(name) || [], fn]); } removeEventListener() {}
    focus() { active = this; } showModal() { this.open = true; } close() { this.open = false; return this.emit('close'); }
    querySelectorAll(tag) { return this.children.flatMap(child => [...(child.tagName === tag.toUpperCase() ? [child] : []), ...child.querySelectorAll(tag)]); }
    emit(name, extra = {}) { return Promise.all((this.events.get(name) || []).map(fn => fn({preventDefault() {}, ...extra}))); }
  }
  for (const match of html.matchAll(/<([a-z0-9]+)\b([^>]*\bid="([^"]+)"[^>]*)>/g)) { const node = new Element(match[1], match[3]); node.hidden = /\bhidden\b/.test(match[2]); node.disabled = /\bdisabled\b/.test(match[2]); nodes.set(match[3], node); }
  const filters = ['all', 'queued', 'claimed', 'finished'].map(filter => { const node = new Element('button'); node.dataset.filter = filter; return node; });
  const document = {getElementById: id => { assert(nodes.has(id), id); return nodes.get(id); }, createElement: tag => new Element(tag), querySelectorAll: () => filters, documentElement: new Element('html'), get activeElement() { return active; }};
  const f = {nodes, events, timers, requests:[], pending:[], posts:[], tasks:[task(2,null),task(1)], operators:new Map(), estimate:estimate(), status:{active:null,recovery_required:false,diagnostic:null}, postMode:'success', operatorError:0, estimateError:0, delay:()=>false, ignoreAbort:false, responseQuota:null};
  for (const t of f.tasks) f.operators.set(t.id,operator(t));
  const $ = id => nodes.get(id); f.$ = $;
  f.resourceReads = () => f.requests.filter(r=>r.url.startsWith('/api/resources')||r.url.endsWith('/operator'));
  f.login = async () => { $('token').value='test-token'; $('username').value='operator'; $('password').value='password'; await $('auth-form').emit('submit'); await settle(); };
  f.select = async id => { await $('task-list').querySelectorAll('button').find(b=>b.dataset.taskId===String(id)).emit('click'); await settle(); };
  f.resolve = url => { const i=f.pending.findIndex(p=>p.url===url); assert(i>=0,'missing '+url); f.pending.splice(i,1)[0].resolve(); };
  f.flush = async () => { for (const [id,timer] of [...timers]) if(timer.milliseconds===2000){timers.delete(id);timer.callback();} await settle(); };
  async function fetch(url, opts) {
    f.requests.push({url,opts}); let data,status=200;
    assert.equal(opts.headers.Authorization,authMode==='bearer'&&url.startsWith('/api/')?'Bearer test-token':undefined);
    if(url==='/auth/status')data={mode:authMode,authenticated:false};
    else if(url==='/auth/login')data={authenticated:true};
    else if(url==='/auth/logout')data={authenticated:false};
    else if(url==='/api/config')data={repositories:['repo','other'],agents:['agent'],tests:['test'],workflows:[{name:'review / flow',repository:'repo',developer:'agent',reviewer:'agent',test:'test',max_repairs:0}]};
    else if(url==='/api/status')data=f.status;
    else if(url==='/api/tasks'&&opts.method==='GET')data=f.tasks;
    else if(url.startsWith('/api/resources?')){data=f.estimate;if(f.estimateError){status=f.estimateError;data={error:'estimate unavailable'};}}
    else if(url.endsWith('/operator')){data=f.operators.get(Number(url.split('/').at(-2)));if(f.operatorError){status=f.operatorError;data={error:'operator unavailable'};}}
    else if(opts.method==='POST'){
      const body=JSON.parse(opts.body); f.posts.push({url,body});
      if(f.postMode==='abort')throw new TypeError('lost response');
      if(['401','422'].includes(f.postMode)){status=Number(f.postMode);data={error:'host policy changed'};}
      else {
        const parent=url==='/api/tasks'?null:Number(url.split('/').at(-2)),old=parent&&f.tasks.find(t=>t.id===parent),job=parent?{...JSON.parse(old.payload),...(body.workspace_quota_bytes===undefined?{}:{workspace_quota_bytes:body.workspace_quota_bytes}),continuation:{predecessor_task_id:parent,...(url.endsWith('/continue-review')?{review_only:{}}:{})}}:body.job;
        if(parent&&f.responseQuota!==null)job.workspace_quota_bytes=f.responseQuota;
        data={...task(Math.max(...f.tasks.map(t=>t.id))+1,null),key:body.key,payload:JSON.stringify(job)};
        f.tasks.unshift(data); const op=operator(data);op.resources.quota_bytes=job.workspace_quota_bytes??1000;f.operators.set(data.id,op);
        if(parent){old.continuation_status={successor_id:data.id};f.operators.get(parent).recovery.successor_id=data.id;f.operators.get(parent).recovery.actions=[];}
      }
    } else data=f.tasks.find(t=>t.id===Number(url.split('/').at(-1)));
    const snapshot=clone(data),response={ok:status===200,status,json:async()=>clone(snapshot)};
    if(f.delay(url,opts))return new Promise((resolve,reject)=>{f.pending.push({url,resolve:()=>resolve(response)});if(!f.ignoreAbort)opts.signal.addEventListener('abort',()=>{const e=new Error('abort');e.name='AbortError';reject(e);});});
    return response;
  }
  const context = {console,document,window:{matchMedia:()=>({matches:false,addEventListener(){}}),addEventListener:(name,fn)=>events.set(name,fn)},navigator:{},fetch,crypto:webcrypto,AbortController,TextEncoder,Uint8Array,Date,Error,JSON,Array,String,Number,Boolean,Set,Map,encodeURIComponent,setTimeout:(callback,milliseconds)=>{const id=++timerId;timers.set(id,{callback,milliseconds});return id;},clearTimeout:id=>timers.delete(id)};
  Object.defineProperties(context,{localStorage:{get(){throw Error('must not use storage')}},sessionStorage:{get(){throw Error('must not use storage')}}});
  vm.runInNewContext(script,context);return f;
}
(async()=>{
  const f=fixture(),$=f.$;await settle();assert.equal(f.resourceReads().length,0);await f.login();assert.equal(f.resourceReads().length,1);assert.equal(f.resourceReads()[0].url,'/api/tasks/2/operator');
  assert($('workspace-quota').disabled);await $('refresh').emit('click');await f.flush();assert.equal(f.resourceReads().length,1,'list polling must never scan resources');
  // Default submissions retain the legacy absent-field wire shape.
  $('requirements').value='default';await $('task-form').emit('submit');assert(!Object.hasOwn(f.posts.at(-1).body.job,'workspace_quota_bytes'));
  await $('resource-read').emit('click');assert(!$('workspace-quota').disabled);assert.match($('resource-estimate').textContent,/宿主策略上限：1000 B/);assert.match($('resource-estimate').textContent,/初始总量估算：220 B/);
  const attack='<img src=x onerror=alert(1)>';f.estimate.initial_estimate={...f.estimate.initial_estimate,complete:false,estimated_initial_bytes:null,git_metadata_reference_bytes:null,notes:[attack]};await $('resource-read').emit('click');assert.match($('resource-estimate-status').textContent,/估算不完整/);assert.match($('resource-estimate').textContent,/初始总量估算：未知/);assert($('resource-estimate').textContent.includes(attack));assert.equal($('resource-estimate').querySelectorAll('img').length,0);
  const before=f.posts.length;for(const value of ['-1','0','1.5','1001','9007199254740992']){$('workspace-quota').value=value;$('requirements').value='invalid';await $('task-form').emit('submit');assert.equal(f.posts.length,before);assert.match($('form-message').textContent,/正整数/);}
  // Initial chosen quota and exact key survive lost responses, clicks and auth interruptions.
  $('workspace-quota').value='500';$('requirements').value='frozen custom';f.postMode='abort';await $('task-form').emit('submit');const original=clone(f.posts.at(-1));assert.equal(original.body.job.workspace_quota_bytes,500);assert($('workspace-quota').disabled);$('workspace-quota').value='999';await $('task-form').emit('submit');assert.deepEqual(f.posts.at(-1),original);
  f.postMode='401';await $('task-form').emit('submit');assert(!$('auth-panel').hidden);f.estimate.host_policy_cap_bytes=300;await f.login();assert.equal($('workspace-quota').value,'500');assert($('workspace-quota').disabled);f.postMode='422';await $('task-form').emit('submit');assert.deepEqual(f.posts.at(-1),original);assert.match($('form-message').textContent,/提交被拒绝/);assert($('workspace-quota').disabled);assert.equal($('workspace-quota').value,'');await $('resource-read').emit('click');assert(!$('workspace-quota').disabled);$('workspace-quota').value='500';await $('task-form').emit('submit');assert.match($('form-message').textContent,/宿主策略上限/);$('workspace-quota').value='';f.postMode='success';
  $('workflow').value='review / flow';await $('workflow').emit('change');await $('resource-read').emit('click');assert.equal(f.resourceReads().at(-1).url,'/api/resources?repository=repo&workflow=review%20%2F%20flow');$('workflow').value='';await $('workflow').emit('change');
  // An old repository response cannot authorize a quota for a newer selection.
  f.delay=url=>url.startsWith('/api/resources');f.ignoreAbort=true;const stale=$('resource-read').emit('click');await settle();$('repository').value='other';await $('repository').emit('change');f.resolve('/api/resources?repository=repo');await stale;assert($('workspace-quota').disabled);assert.equal($('resource-estimate').textContent,'');f.delay=()=>false;f.ignoreAbort=false;$('repository').value='repo';await $('repository').emit('change');
  // Structured host failure and retained state are rendered literally; no log parsing.
  await f.select(1);assert(!$('retry-task').disabled);assert(!$('review-task').hidden);assert.match($('operator-failure').textContent,/workspace_quota_exceeded/);assert.match($('operator-retained').textContent,/已保留且不可改写/);assert.match($('operator-resources').textContent,/150 B/);
  const op=f.operators.get(1);op.failure={code:attack,stage:attack,cause:attack};op.resources.usage={logical_bytes:120,complete:false,measured_at:1700000000,reason:attack};op.recovery.actions=[];op.recovery.blocked_reason='未知进程或外部发布需要宿主核对';await $('operator-read').emit('click');assert($('retry-task').disabled);assert($('review-task').hidden);assert.match($('operator-resources').textContent,/至少 120 B/);assert.match($('operator-resources').textContent,/观测不完整/);assert.equal($('operator-failure').querySelectorAll('img').length,0);assert($('operator-failure').textContent.includes(attack));
  op.resources.usage.logical_bytes=null;await $('operator-read').emit('click');assert.match($('operator-resources').textContent,/当前逻辑用量未知/);
  f.operatorError=503;await $('operator-read').emit('click');assert($('retry-task').disabled);assert.match($('operator-status').textContent,/恢复资格未知/);f.operatorError=0;
  // Wrong task/generation and late reads never replace the current detail.
  op.task_id=99;await $('operator-read').emit('click');assert($('retry-task').disabled);assert.match($('operator-status').textContent,/不匹配/);op.task_id=1;op.generation=9;await $('operator-read').emit('click');assert($('retry-task').disabled);op.generation=1;
  f.delay=url=>url.endsWith('/operator');f.ignoreAbort=true;const first=f.select(1);await settle();const second=f.select(2);await settle();f.resolve('/api/tasks/2/operator');await second;f.resolve('/api/tasks/1/operator');await first;assert.equal($('detail-title').textContent,'任务 #2');assert.equal($('operator-failure').textContent.includes(attack),false);f.delay=()=>false;f.ignoreAbort=false;
  // At-cap and source snapshot limits are distinct; neither invents bump headroom.
  op.failure={code:'source_snapshot_limit',stage:'snapshot',cause:'Source exceeds independent snapshot cap'};op.resources.quota_bytes=1000;op.resources.usage={logical_bytes:900,complete:true,measured_at:1700000000,reason:null};op.recovery.actions=[{...action(),quota_increase_allowed:false,quota_increase_required:false,min_quota_bytes:null}];op.recovery.blocked_reason='Source snapshot cannot be fixed by workspace quota';await f.select(1);assert.match($('operator-failure').textContent,/source_snapshot_limit/);assert.match($('operator-recovery').textContent,/经过授权的宿主配置变更/);await $('retry-task').emit('click');assert($('retry-quota').disabled);assert.match($('retry-quota-hint').textContent,/已达宿主策略上限/);await $('retry-dismiss').emit('click');
  // Quota bumps are explicit, bounded, and included in the confirmation summary.
  f.operators.set(1,operator(f.tasks.find(t=>t.id===1)));await $('operator-read').emit('click');await $('retry-task').emit('click');await $('retry-confirm').emit('click');assert($('retry-dialog').open);assert.match($('retry-dialog-error').textContent,/宿主要求显式提高容量/);
  for(const value of ['100','150','1001','200.5']){$('retry-quota').value=value;await $('retry-confirm').emit('click');assert($('retry-dialog').open);assert.match($('retry-dialog-error').textContent,/容量必须严格提高/);}
  $('retry-quota').value='200';await $('retry-quota').emit('input');assert.match($('retry-quota-summary').textContent,/100 B → 200 B；宿主上限 1000 B/);f.postMode='abort';await $('retry-confirm').emit('click');const retry=clone(f.posts.at(-1));assert.equal(retry.body.workspace_quota_bytes,200);await $('retry-task').emit('click');assert($('retry-quota').disabled);assert.equal($('retry-quota').value,'200');const unresolvedError=$('detail-error').textContent;$('retry-dialog-error').textContent='frozen request notice';$('retry-quota').value='800';await $('retry-quota').emit('input');assert.equal($('retry-dialog-error').textContent,'frozen request notice');assert.equal($('detail-error').textContent,unresolvedError);f.postMode='401';await $('retry-confirm').emit('click');assert.deepEqual(f.posts.at(-1),retry);await f.login();await f.select(1);await $('retry-task').emit('click');assert.equal($('retry-quota').value,'200');await $('retry-dismiss').emit('click');
  // A different tab's durable reservation is authoritative, including mode/focus/quota/key.
  const saved={action_id:'continue_review',key:'other-tab-key',workspace_quota_bytes:300,revalidate_tests:true,review_focus:'server saved focus'};f.operators.get(1).recovery.reserved_request=saved;await $('operator-read').emit('click');assert($('retry-task').disabled);await $('review-task').emit('click');assert.equal($('retry-quota').value,'300');assert($('retry-quota').disabled);assert.equal($('review-focus').value,'server saved focus');assert($('review-focus').disabled);f.postMode='success';f.delay=(url,opts)=>opts.method==='POST';const submitting=$('retry-confirm').emit('click');await settle();await $('retry-confirm').emit('click');const savedPost=f.posts.at(-1);assert.equal(savedPost.url,'/api/tasks/1/continue-review');assert.equal(savedPost.body.key,'other-tab-key');assert.equal(savedPost.body.workspace_quota_bytes,300);assert.equal(savedPost.body.review_focus,'server saved focus');f.resolve(savedPost.url);await submitting;f.delay=()=>false;assert.match($('detail-meta').textContent,/300 B/);await f.select(1);assert($('retry-task').hidden);assert($('review-task').hidden);assert(!$('continuation-next').hidden);
  // Live host policy changes and navigation fence an already open confirmation.
  const t=task(20);f.tasks.unshift(t);f.operators.set(20,operator(t));await $('refresh').emit('click');await f.select(20);await $('retry-task').emit('click');$('retry-quota').value='400';f.operators.get(20).resources.host_policy_cap_bytes=250;f.operators.get(20).recovery.actions[0].max_quota_bytes=250;await $('operator-read').emit('click');const postsBefore=f.posts.length;await $('retry-confirm').emit('click');assert.equal(f.posts.length,postsBefore);assert.match($('retry-dialog-error').textContent,/宿主允许/);await f.select(2);await $('retry-confirm').emit('click');assert.equal(f.posts.length,postsBefore);assert(!$('retry-dialog').open);
  // Real unknown claims block even if an incorrect server response advertises an action.
  const unknown=task(21,'unknown');unknown.state='claimed';f.tasks.unshift(unknown);f.operators.set(21,operator(unknown));await $('refresh').emit('click');await f.select(21);assert($('retry-task').disabled);assert($('review-task').disabled);assert(!$('detail-warning').hidden);
  // Logout and browser history restoration clear resource information and fence stale reads.
  await f.select(20);f.delay=url=>url.endsWith('/operator');f.ignoreAbort=true;const late=$('operator-read').emit('click');await settle();await $('logout').emit('click');f.resolve('/api/tasks/20/operator');await late;assert($('detail-operator').hidden);assert.equal($('operator-resources').textContent,'');assert.equal($('resource-estimate').textContent,'');assert.equal($('workspace-quota').value,'');f.delay=()=>false;await f.login();await $('resource-read').emit('click');$('workspace-quota').value='200';f.events.get('pagehide')();f.events.get('pageshow')({persisted:true});assert(!$('auth-panel').hidden);assert.equal($('workspace-quota').value,'');assert.equal($('resource-estimate').textContent,'');
  // Repo/workflow changes drop unsubmitted quotas; failed estimates still allow default submission.
  const g=fixture(),q=g.$;await settle();await g.login();await q('resource-read').emit('click');q('workspace-quota').value='500';q('repository').value='other';await q('repository').emit('change');assert.equal(q('workspace-quota').value,'');g.estimateError=503;await q('resource-read').emit('click');assert(q('workspace-quota').disabled);q('requirements').value='other repository default';await q('task-form').emit('submit');assert.equal(g.posts.at(-1).body.job.repository,'other');assert(!Object.hasOwn(g.posts.at(-1).body.job,'workspace_quota_bytes'));
  g.estimateError=0;await q('resource-read').emit('click');q('workspace-quota').value='200';q('workflow').value='review / flow';await q('workflow').emit('change');assert.equal(q('workspace-quota').value,'');g.estimateError=503;await q('resource-read').emit('click');q('requirements').value='workflow default';await q('task-form').emit('submit');assert.equal(g.posts.at(-1).body.job.workflow,'review / flow');assert(!Object.hasOwn(g.posts.at(-1).body.job,'workspace_quota_bytes'));
  // A failed same-selection reread retains the choice for review but permits clearing it.
  g.estimateError=0;await q('resource-read').emit('click');q('workspace-quota').value='200';g.estimateError=503;await q('resource-read').emit('click');assert.equal(q('workspace-quota').value,'200');assert(!q('workspace-quota').disabled);assert.match(q('quota-hint').textContent,/可清空/);q('requirements').value='clear unverified quota';const beforeClear=g.posts.length;await q('task-form').emit('submit');assert.equal(g.posts.length,beforeClear);q('workspace-quota').value='';await q('workspace-quota').emit('input');await q('task-form').emit('submit');assert(!Object.hasOwn(g.posts.at(-1).body.job,'workspace_quota_bytes'));
  // Recorded prior quota and the no-override retry quota are distinct after host-policy changes.
  const h=fixture(),hq=h.$;h.operators.get(1).recovery.inherited_quota_bytes=1000;h.operators.get(1).recovery.actions.forEach(a=>a.quota_increase_required=false);await settle();await h.login();await h.select(1);assert.match(hq('operator-resources').textContent,/已记录任务容量100 B/);assert.match(hq('operator-resources').textContent,/无覆盖续接容量1000 B/);await hq('retry-task').emit('click');assert.match(hq('retry-quota-summary').textContent,/100 B → 无覆盖续接 1000 B/);await hq('retry-confirm').emit('click');assert.equal(h.posts.at(-1).url,'/api/tasks/1/retry');assert(!Object.hasOwn(h.posts.at(-1).body,'workspace_quota_bytes'));
  const k=fixture(),kq=k.$;k.operators.get(1).resources.quota_bytes=null;k.operators.get(1).recovery.inherited_quota_bytes=1000;k.operators.get(1).recovery.actions[0].min_quota_bytes=200;k.operators.get(1).failure={code:'workspace_quota_exceeded',stage:'admission',cause:'planned copy',required_bytes:333,limit_bytes:100};await settle();await k.login();await k.select(1);assert.match(kq('operator-resources').textContent,/已记录任务容量未知/);assert.match(kq('operator-failure').textContent,/失败时已知所需容量：333 B/);assert.match(kq('operator-failure').textContent,/失败时适用上限：100 B/);await kq('retry-task').emit('click');kq('retry-quota').value='199';await kq('retry-confirm').emit('click');assert.equal(k.posts.length,0);kq('retry-quota').value='200';await kq('retry-confirm').emit('click');assert.equal(k.posts.at(-1).body.workspace_quota_bytes,200);
  // Planned-copy admission requires a bump even with low current usage; only the server flag decides.
  const planned=fixture(),pq=planned.$,po=planned.operators.get(1);po.resources.usage.logical_bytes=10;po.failure={code:'workspace_quota_exceeded',stage:'admission',cause:'opaque diagnosis without capacity keywords',required_bytes:333,limit_bytes:100};po.recovery.actions.forEach(a=>{a.min_quota_bytes=333;a.quota_increase_required=true;});await settle();await planned.login();await planned.select(1);await pq('retry-task').emit('click');assert.match(pq('retry-quota-hint').textContent,/不能留空/);assert.match(pq('retry-quota-summary').textContent,/必须显式提高/);await pq('retry-confirm').emit('click');assert.equal(planned.posts.length,0);assert.match(pq('retry-dialog-error').textContent,/宿主要求显式提高容量/);pq('retry-quota').value='332';await pq('retry-confirm').emit('click');assert.equal(planned.posts.length,0);pq('retry-quota').value='333';await pq('retry-quota').emit('input');assert(pq('retry-dialog-error').hidden);assert.equal(pq('retry-dialog-error').textContent,'');await pq('retry-confirm').emit('click');assert.equal(planned.posts.at(-1).body.workspace_quota_bytes,333);
  const advisory=fixture(),aq=advisory.$;advisory.operators.get(1).resources.usage.logical_bytes=999;advisory.operators.get(1).recovery.actions.forEach(a=>a.quota_increase_required=false);await settle();await advisory.login();await advisory.select(1);await aq('retry-task').emit('click');await aq('retry-confirm').emit('click');assert.equal(advisory.posts.at(-1).url,'/api/tasks/1/retry');assert(!Object.hasOwn(advisory.posts.at(-1).body,'workspace_quota_bytes'),'UI must not infer quota requirement from usage or cause');
  for(const mode of ['session','hybrid']){const g=fixture(mode);await settle();await g.login();await g.$('resource-read').emit('click');assert(!g.$('workspace-quota').disabled);await g.$('logout').emit('click');assert(g.$('detail-operator').hidden);assert.equal(g.$('resource-estimate').textContent,'');}
  console.log('PASS: resource UI: bounded detail-only reads, explicit initial quotas, immutable wire retries through auth, server-owned eligibility/reservations, stale-task and policy fencing, unknown/incomplete observations, source-vs-workspace limits, retained results, safe DOM and logout/history cleanup');
})().catch(error=>{console.error(error);process.exitCode=1});
